name: Release
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  workflow_dispatch:

env:
  CRATE_NAME: coman
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1
jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: coman
            name: coman-Linux-x86_64-musl.tar.gz
            cargo_command: cargo
            squash: true

          - os_name: Linux-aarch64
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            bin: coman
            name: coman-Linux-aarch64-musl.tar.gz
            cargo_command: cargo
            squash: true

          - os_name: Windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc
            bin: coman.exe
            name: coman-Windows-aarch64.zip
            cargo_command: cargo
            squash: false

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: coman
            name: coman-Darwin-x86_64.tar.gz
            cargo_command: cargo
            squash: false

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
          cache-workspace-crates: "true"
      - name: Install oas3-gen
        run: cargo install oas3-gen@0.21.1
      - name: Install build dependencies on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools openssl libssl-dev squashfs-tools
        if: contains(matrix.platform.os, 'ubuntu')
      - name: Build binary (*nix)
        shell: bash
        run: |
          ${{ matrix.platform.cargo_command }} build --locked --release --target ${{ matrix.platform.target }}
        if: ${{ !contains(matrix.platform.os, 'windows') }}
      - name: Build binary (Windows)
        # We have to use the platform's native shell. If we use bash on
        # Windows then OpenSSL complains that the Perl it finds doesn't use
        # the platform's native paths and refuses to build.
        shell: powershell
        run: |
          & ${{ matrix.platform.cargo_command }} build --locked --release --target ${{ matrix.platform.target }}
        if: contains(matrix.platform.os, 'windows')
      - name: Strip binary
        shell: bash
        run: |
          strip target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: ${{ !( matrix.platform.target == 'aarch64-pc-windows-msvc') }}
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          if [[ "${{ matrix.platform.squash }}" == "true" ]]; then
            mksquashfs ${{ matrix.platform.bin }} ../../../coman_${{matrix.platform.os_name}}.sqsh
          fi
          cd -
      - uses: actions/upload-artifact@v4
        with:
          name: "${{matrix.platform.os_name}}"
          path: |
            coman*.gz
            coman*.zip
            coman*.sqsh
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "coman*"
          body_path: Changes.md
        if: startsWith( github.ref, 'refs/tags/v' )
